---
- hosts: remote
  tasks:
    - name: create file
      lineinfile:
        path: /home/ansible/hostname
        create: yes
        line: "{{ alias_name }}"
    - name: access the magic variable
      lineinfile:
        path: /home/ansible/hostname
        line: "{{ hostvars['localhost']['ansible_default_ipv4']['address'] }}"
