---
- hosts: centos
  tasks:
    - name: Create working directory
      file:
        name: "{{ working_dir }}"
        state: directory
    - name: Write Contents to file
      lineinfile:
        path: "{{ working_dir }}/services.txt"
        create: yes
        line: "{{ service_list }} {{ operating_system }} {{ alias_name }}" 
    - name: view disk info and pass to register variable
      command: ls -la "{{ shared_paths['homedir'] }}"
      register: cmd_disk_output
    - name: Write disk info into file using register variable
      copy:
        content: "{{ cmd_disk_output }}"
        dest: "{{ working_dir }}/cmd_output.txt"
