---  # Vault Example
- hosts: localhost
  vars_files:
    /home/ansible/variable-passwords.txt
  tasks:
    - name: Add secret text of open.txt
      lineinfile:
        path: /home/ansible/open.txt
        create: yes
        line: "{{ password }}"
      no_log: true 
